
function mintsData = gpvtgAMRead(fileName,timeSpan)
    
    %% Import data from text file
    % Script for importing data from the following text file:
    %
    %    filename: /media/teamlary/teamlary1/gitHubRepos/airMarMintsML/firmware/dataProcessing/MINTS_001e0610c0e4_GPVTG_2020_08_12.csv
    %
    % Auto-generated by MATLAB on 28-Aug-2020 11:56:01

    %% Setup the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 11);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["dateTime", "courseOGTrue", "relativeToTN", "courseOGMagnetic", "relativeToMN", "speedOverGroundKnots", "SOGKUnits", "speedOverGroundKMPH", "SOGKMPHUnits", "mode", "checkSum"];
    opts.VariableTypes = ["datetime", "double", "categorical", "double", "categorical", "double", "categorical", "double", "categorical", "categorical", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, ["relativeToTN", "relativeToMN", "SOGKUnits", "SOGKMPHUnits", "mode"], "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "dateTime", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");

    % Import the data
    mintsData = readtable(fileName, opts);
    mintsData.dateTime.TimeZone = "utc";

    mintsData = removevars( mintsData,{...    
                                'relativeToTN'        ,...
                                'relativeToMN'       ,...
                                'SOGKUnits'           ,...
                                'SOGKMPHUnits'        ,...
                                'mode'                ,...
                                'checkSum'            ,...
                                });

    mintsData   =  retime(table2timetable(mintsData),'regular',@nanmean,'TimeStep',timeSpan);
    
    %% Clear temporary variables
    clear opts
    
end
