
function mintsData =hchdtAMRead(fileName,timeSpan)

    %% Import data from text file
    % Script for importing data from the following text file:

    % Auto-generated by MATLAB on 31-Aug-2020 08:01:46

    %% Setup the Import Options and import the data
    opts = delimitedTextImportOptions("NumVariables", 4);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = ",";

    % Specify column names and types
    opts.VariableNames = ["dateTime", "heading", "HID", "checkSum"];
    opts.VariableTypes = ["datetime", "double", "categorical", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";

    % Specify variable properties
    opts = setvaropts(opts, "HID", "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "dateTime", "InputFormat", "yyyy-MM-dd HH:mm:ss.SSS");
    opts = setvaropts(opts, "checkSum", "TrimNonNumeric", true);
    opts = setvaropts(opts, "checkSum", "ThousandsSeparator", ",");

    % Import the data
    mintsData = readtable(fileName, opts);
    mintsData = removevars( mintsData,{'HID'    ,...
                                      'checkSum'});
        mintsData.dateTime.TimeZone = "utc";


    mintsData   =  retime(table2timetable(mintsData),'regular',@nanmean,'TimeStep',timeSpan);

    %% Clear temporary variables
    clear opts
    
end